### ISSUE TITLE
Added polls label on issue without a poll

### ISSUE THREAD

**Issue by bkeepers** [evenchange4/gh-polls-bot#13]
This issue includes a URL that has `polls`, which appeared to trigger the polls app: https://github.com/probot/probot.github.io/issues/95

e.g.

```
[Take my poll](https://example.com/poll/vote)
```

**Comment by bkeepers** [comment]
Actually, I misunderstood what triggered it. Here's the code in question

```
Errno::ENOENT: No such file or directory @ rb_sysopen -
/home/travis/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/bundler/templates/Executable
An error occurred while installing concurrent-ruby (1.0.5), and Bundler cannot
continue.
Make sure that `gem install concurrent-ruby -v '1.0.5'` succeeds before
bundling.
```

It appears that the line starting with `/home/travis/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/bundler/templates/Executable` is triggering the poll behavior.

**Comment by evenchange4** [comment]
This should be fixed now. Thanks for reporting!

Close it via [RegExp bugfix PR#14](https://github.com/evenchange4/gh-polls-bot/pull/14). Please feel free to reopen this issue if the problem still occurs.
