### ISSUE TITLE
No poll is being created

### ISSUE THREAD

**Issue by andrey-helldar** [evenchange4/gh-polls-bot#26]
I added the [Polls app](https://github.com/apps/polls) to the [organization](https://github.com/Laraberries).

It is enabled in the settings. I add text to the description and comments of the problem, but the survey is [not generated](https://github.com/Laraberries/php-fpm/issues/1).

What am I doing wrong?

![image](https://user-images.githubusercontent.com/10347617/94053798-7759d180-fde3-11ea-9394-44b0ec64227b.png)

![image](https://user-images.githubusercontent.com/10347617/94053829-7f197600-fde3-11ea-8519-04fce59b6d9c.png)

Also here: https://github.com/Laravel-Lang/lang/issues/1347

**Comment by fawazahmed0** [comment]
I too faced this, just testing polls in this repo:
/polls Option1 'Option 2' "Option 3"

**Comment by fawazahmed0** [comment]
Ok, anyone facing the issue can use [this polls](https://github.com/apex/gh-polls):

1. Just install [Go](https://golang.org/dl/)

2.  Install polls package in your pc:
`go get github.com/apex/gh-polls/cmd/polls`

3.  Create a poll and markdown will be automatically copied to clipboard.
`polls new "Fawaz is cool" "Andrey is awesome"`

4. Paste the auto copied markdown:

[![](https://api.gh-polls.com/poll/01EKFYV6MB64AHNNM8BNCD5BSR/Fawaz%20is%20Cool)](https://api.gh-polls.com/poll/01EKFYV6MB64AHNNM8BNCD5BSR/Fawaz%20is%20Cool/vote)
[![](https://api.gh-polls.com/poll/01EKFYV6MB64AHNNM8BNCD5BSR/Andrey%20is%20Awesome)](https://api.gh-polls.com/poll/01EKFYV6MB64AHNNM8BNCD5BSR/Andrey%20is%20Awesome/vote)


**Update**: Easy method, Just use [this](https://app.gh-polls.com/)

**Comment by alanhamlett** [comment]
> **Update**: Easy method, Just use [this](https://app.gh-polls.com/)

That no longer works, so I built my own:
https://wakatime.com/polls
