### ISSUE TITLE
Add gh-polls-bot to probot.github.io

### ISSUE THREAD

**Issue by anglinb** [evenchange4/gh-polls-bot#5]
👋 @evenchange4 this is awesome 🎉 🎉  Would love to add this to the listing of probot apps on probot.github.io. 

If you would like to get it added, feel free to open a PR on [probot/probot.github.io](https://github.com/probot/probot.github.io). Here's an example of the information need to get it listed: https://github.com/probot/probot.github.io/pull/78

**Comment by evenchange4** [comment]
Sure, I created PR https://github.com/probot/probot.github.io/pull/91. Awesome Probot!

**Comment by anglinb** [comment]
Thanks for adding this @evenchange4! https://probot.github.io/apps/polls/ 👀
